use std::cell::RefCell;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use tower_lsp_server::ls_types::*;

pub fn hash_bytes(data: &[u8]) -> u64 {
    let mut hasher = DefaultHasher::new();
    data.hash(&mut hasher);
    hasher.finish()
}

/// Thread-local cache of `\n` byte offsets for the last-seen source
/// buffer. `ts_point_to_position` / `ts_node_to_range` hit this path
/// hundreds of times per call to `build_summary`; without the cache
/// each hit scanned the full source from offset 0 to find the start
/// of a given row, making the outer summary build O(N²) in source
/// size. On 1.3 MB files with thousands of top-level statements that
/// was ~20 s in release (effectively a hang in debug builds).
///
/// Key invariants:
/// - Keyed by `(ptr, len, first_byte, last_byte)` — the first/last
///   byte pair adds ~16 bits of cheap entropy on top of address +
///   length. ABA collisions would require a freshly allocated
///   different source to land at the exact same heap address with
///   the exact same length AND identical first/last bytes — which
///   is essentially impossible in practice (UE4-style autogenerated
///   dumps always differ across files) while costing two byte reads
///   per call. Worst case stale cache is still self-correcting on
///   the next distinct source.
/// - Stored per thread — rayon workers each maintain their own
///   cache with zero locking, so concurrent indexing of different
///   files stays contention-free.
/// - Access is guarded by a `RefCell`, but no public API exposes a
///   closure that sees the live vector — `byte_offset_of_line` is
///   the sole consumer and completes its lookup before releasing
///   the borrow. This removes the re-entrancy footgun of an
///   earlier `with_line_starts(|starts| ...)` helper where a
///   caller could accidentally recurse into another cache access
///   while holding the `borrow_mut`.
#[derive(Default)]
struct LineIndexCache {
    key: Option<(usize, usize, u8, u8)>,
    line_starts: Vec<usize>,
}

thread_local! {
    static LINE_INDEX_CACHE: RefCell<LineIndexCache> = RefCell::new(LineIndexCache::default());
}

/// Convert a tree-sitter `Point` (row + BYTE-column into that row) into an
/// LSP `Position` where `character` is a UTF-16 code-unit offset — the
/// default LSP position encoding.
pub fn ts_point_to_position(point: tree_sitter::Point, source: &[u8]) -> Position {
    let row = point.row;
    let byte_col = point.column;
    let line_bytes = line_bytes_for_row(source, row);
    let utf16_col = byte_col_to_utf16_col(line_bytes, byte_col);
    Position {
        line: row as u32,
        character: utf16_col,
    }
}

/// Convert a tree-sitter `Node`'s span to an LSP `Range` with UTF-16-unit
/// columns. Callers always have `source` on hand; pass it through so the
/// conversion happens once at the tree-sitter boundary and every stored
/// `Range` is "LSP-ready".
pub fn ts_node_to_range(node: tree_sitter::Node, source: &[u8]) -> Range {
    Range {
        start: ts_point_to_position(node.start_position(), source),
        end: ts_point_to_position(node.end_position(), source),
    }
}

pub fn node_text<'a>(node: tree_sitter::Node<'a>, source: &'a [u8]) -> &'a str {
    node.utf8_text(source).unwrap_or("<error>")
}

pub fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.replace('\n', "\\n")
    } else {
        let mut cut = max;
        while cut > 0 && !s.is_char_boundary(cut) {
            cut -= 1;
        }
        format!("{}...", &s[..cut].replace('\n', "\\n"))
    }
}

/// Convert an LSP `Position` (`character` = UTF-16 code units into its line)
/// into a byte offset into `source`.
pub fn position_to_byte_offset(source: &str, pos: Position) -> Option<usize> {
    let bytes = source.as_bytes();
    let line_start = byte_offset_of_line(bytes, pos.line as usize)?;
    let line_bytes = line_bytes_after(bytes, line_start);
    let col_byte = utf16_col_to_byte_col(line_bytes, pos.character);
    let abs = line_start + col_byte;
    if abs <= source.len() {
        Some(abs)
    } else {
        None
    }
}

/// Returns the byte offset of the start of `row` (0-indexed) in `source`,
/// or `None` if `row` is beyond the last newline.
fn byte_offset_of_line(source: &[u8], row: usize) -> Option<usize> {
    // Cached lookup: O(1) after the first call per source buffer.
    // Previously this was an O(N) scan from offset 0 on every call,
    // which quadratic-blew summary_builder on large files.
    //
    // `line_starts` always starts with [0, ...] and pushes one entry
    // per `\n` (offset of the byte AFTER the newline). So:
    //   - For "a\nb\nc" (no trailing `\n`) → [0, 2, 4] → rows 0,1,2.
    //   - For "a\nb\n"  (trailing `\n`)    → [0, 2, 4] → rows 0,1,2,
    //     where row 2 (the position past the final newline, i.e. EOF
    //     beginning of a virtual empty line) resolves to source.len().
    //
    // Rows out of range (e.g. row beyond actual line count for a file
    // without trailing `\n`) return `None` — matching the legacy
    // linear-scan behavior used by the rest of the codebase.
    //
    // Cache reuse is keyed by (ptr, len, first_byte, last_byte). The
    // capacity hint `len / 40 + 16` is sized for hand-written Lua
    // (~40 bytes/line average); autogenerated files like UE4 enum
    // dumps run closer to 200 bytes/line and over-allocate by ~4x
    // (~26 KB wasted per worker for a 1.3 MB file), which is far
    // cheaper than a second reallocation during the scan.
    LINE_INDEX_CACHE.with(|cell| {
        let mut c = cell.borrow_mut();
        let first = source.first().copied().unwrap_or(0);
        let last = source.last().copied().unwrap_or(0);
        let key = (source.as_ptr() as usize, source.len(), first, last);
        if c.key != Some(key) {
            c.line_starts.clear();
            c.line_starts.reserve(source.len() / 40 + 16);
            c.line_starts.push(0);
            for (i, &b) in source.iter().enumerate() {
                if b == b'\n' {
                    c.line_starts.push(i + 1);
                }
            }
            c.key = Some(key);
        }
        c.line_starts.get(row).copied()
    })
}

/// Return the slice of `source` from `start` up to (but not including) the
/// next `\n` or the end of input.
fn line_bytes_after(source: &[u8], start: usize) -> &[u8] {
    let mut end = start;
    while end < source.len() && source[end] != b'\n' {
        end += 1;
    }
    &source[start..end]
}

/// Return the bytes of the `row`-th line in `source` (without the trailing
/// newline). If `row` is past the last line, returns an empty slice.
fn line_bytes_for_row(source: &[u8], row: usize) -> &[u8] {
    match byte_offset_of_line(source, row) {
        Some(start) => line_bytes_after(source, start),
        None => &[],
    }
}

/// Convert a byte column within `line_bytes` (UTF-8) to a UTF-16 code-unit
/// column. `byte_col` past the end is clamped to the line's UTF-16 length.
pub fn byte_col_to_utf16_col(line_bytes: &[u8], byte_col: usize) -> u32 {
    let clamped = byte_col.min(line_bytes.len());
    // Safety: tree-sitter byte columns align with character boundaries for
    // well-formed UTF-8; invalid sequences fall back to replacement chars.
    let prefix = std::str::from_utf8(&line_bytes[..clamped])
        .unwrap_or_else(|e| std::str::from_utf8(&line_bytes[..e.valid_up_to()]).unwrap_or(""));
    let mut units = 0u32;
    for ch in prefix.chars() {
        units += ch.len_utf16() as u32;
    }
    units
}

/// Convert a byte offset into `source` to an LSP `Position` (row + UTF-16
/// column). Walks the source once to count preceding newlines, then uses
/// `byte_col_to_utf16_col` for the column.
pub fn byte_offset_to_position(source: &[u8], byte_offset: usize) -> Option<Position> {
    if byte_offset > source.len() {
        return None;
    }
    let mut line: u32 = 0;
    let mut line_start = 0usize;
    for (i, &b) in source.iter().take(byte_offset).enumerate() {
        if b == b'\n' {
            line += 1;
            line_start = i + 1;
        }
    }
    let line_bytes_end = source[line_start..]
        .iter()
        .position(|&b| b == b'\n')
        .map_or(source.len(), |p| line_start + p);
    let line_slice = &source[line_start..line_bytes_end];
    let col_in_line_bytes = byte_offset - line_start;
    let character = byte_col_to_utf16_col(line_slice, col_in_line_bytes);
    Some(Position { line, character })
}

/// Convert a UTF-16 code-unit column within `line_bytes` (UTF-8) back to a
/// byte column. Values past end-of-line are clamped to the line length.
pub fn utf16_col_to_byte_col(line_bytes: &[u8], utf16_col: u32) -> usize {
    let line_str = match std::str::from_utf8(line_bytes) {
        Ok(s) => s,
        Err(e) => std::str::from_utf8(&line_bytes[..e.valid_up_to()]).unwrap_or(""),
    };
    let mut remaining = utf16_col;
    let mut bytes = 0usize;
    for ch in line_str.chars() {
        let unit = ch.len_utf16() as u32;
        if remaining < unit {
            break;
        }
        remaining -= unit;
        bytes += ch.len_utf8();
    }
    bytes
}

pub fn find_node_at_position<'a>(
    root: tree_sitter::Node<'a>,
    byte_offset: usize,
) -> Option<tree_sitter::Node<'a>> {
    let mut node = root.descendant_for_byte_range(byte_offset, byte_offset)?;
    while node.kind() != "identifier" {
        node = node.parent()?;
    }
    Some(node)
}

/// Hard ceiling for "walk ancestors looking for X" loops across the
/// codebase. Lua AST ancestor chains for the patterns we inspect
/// (variable / field_expression / function_name / function_call)
/// are at most a handful of levels deep; anything beyond `ANCESTOR_WALK_LIMIT`
/// signals a malformed tree or a pathological source we'd rather
/// bail out of than spin on.
pub const ANCESTOR_WALK_LIMIT: usize = 64;

/// Walk up from `node` calling `pred` on each ancestor; return the
/// first ancestor for which `pred` yields `Some(T)`. Guards against
/// runaway trees by capping depth at [`ANCESTOR_WALK_LIMIT`] and
/// logging a warning via `crate::logger::log` if the cap is hit.
///
/// Note: `node` itself is NOT inspected — the walk starts at
/// `node.parent()`. This matches the common "find an enclosing Xyz"
/// pattern in hover / goto / completion.
pub fn walk_ancestors<'a, T>(
    node: tree_sitter::Node<'a>,
    mut pred: impl FnMut(tree_sitter::Node<'a>) -> Option<T>,
) -> Option<T> {
    let mut current = node;
    for _ in 0..ANCESTOR_WALK_LIMIT {
        let parent = current.parent()?;
        if let Some(v) = pred(parent) {
            return Some(v);
        }
        current = parent;
    }
    crate::logger::log(&format!(
        "[walk_ancestors] hit depth limit ({}) starting at {} — malformed tree?",
        ANCESTOR_WALK_LIMIT,
        node.kind(),
    ));
    None
}

/// Apply an LSP `TextDocumentContentChangeEvent`-style incremental edit to
/// `text`, returning the `InputEdit` needed to tell tree-sitter about the
/// edit. `range` is in LSP coordinates (UTF-16).
///
/// If either endpoint of `range` cannot be resolved (e.g. the client sent a
/// position past end-of-file), we clamp **both** endpoints to `text.len()`
/// and emit the edit as an append at EOF. This is safer than silently
/// inserting at byte 0, which would corrupt the document. A warning is
/// logged so the mismatch is visible in the log file.
pub fn apply_text_edit(
    text: &mut String,
    range: Range,
    new_text: &str,
) -> tree_sitter::InputEdit {
    let raw_start = position_to_byte_offset(text, range.start);
    let raw_end = position_to_byte_offset(text, range.end);

    // Happy path: trust the client's row numbers (the byte offsets above
    // were computed from them anyway). Only fall back to a full-text
    // scan of `byte_offset_to_ts_point` when we clamp to EOF, so editing
    // near the end of a large file doesn't force an O(file_size) rescan
    // for every keystroke.
    let (start_byte, start_point, old_end_byte, old_end_point) =
        match (raw_start, raw_end) {
            (Some(s), Some(e)) if s <= e => {
                let bytes = text.as_bytes();
                let s_line_start =
                    byte_offset_of_line(bytes, range.start.line as usize).unwrap_or(0);
                let e_line_start =
                    byte_offset_of_line(bytes, range.end.line as usize).unwrap_or(s_line_start);
                let s_point = tree_sitter::Point {
                    row: range.start.line as usize,
                    column: s.saturating_sub(s_line_start),
                };
                let e_point = tree_sitter::Point {
                    row: range.end.line as usize,
                    column: e.saturating_sub(e_line_start),
                };
                (s, s_point, e, e_point)
            }
            _ => {
                crate::lsp_log!(
                    "[apply_text_edit] out-of-range Range {:?}/{:?} (text len={}); \
                     clamping to EOF",
                    range.start,
                    range.end,
                    text.len(),
                );
                let p = byte_offset_to_ts_point(text.as_bytes(), text.len());
                (text.len(), p, text.len(), p)
            }
        };

    text.replace_range(start_byte..old_end_byte, new_text);

    let new_end_byte = start_byte + new_text.len();
    let new_end_point = if let Some(last_nl) = new_text.rfind('\n') {
        let newlines = new_text.bytes().filter(|&b| b == b'\n').count();
        let tail_len = new_text.len() - (last_nl + 1);
        tree_sitter::Point {
            row: start_point.row + newlines,
            column: tail_len,
        }
    } else {
        tree_sitter::Point {
            row: start_point.row,
            column: start_point.column + new_text.len(),
        }
    };

    tree_sitter::InputEdit {
        start_byte,
        old_end_byte,
        new_end_byte,
        start_position: start_point,
        old_end_position: old_end_point,
        new_end_position: new_end_point,
    }
}

/// Convert a byte offset in `source` into a tree-sitter `Point` with
/// BYTE column. Used by `apply_text_edit` so the edit's start / old_end
/// positions are always consistent with the text we actually modify, even
/// when the caller's `Position` was out of range and got clamped.
fn byte_offset_to_ts_point(source: &[u8], byte_offset: usize) -> tree_sitter::Point {
    let clamped = byte_offset.min(source.len());
    let mut row = 0usize;
    let mut line_start = 0usize;
    for (i, &b) in source.iter().take(clamped).enumerate() {
        if b == b'\n' {
            row += 1;
            line_start = i + 1;
        }
    }
    tree_sitter::Point {
        row,
        column: clamped - line_start,
    }
}

/// Returns `true` when `ancestor` is, or contains, `descendant` in the
/// tree-sitter AST. Walks from `descendant` upward comparing node IDs.
pub fn is_ancestor_or_equal(ancestor: tree_sitter::Node, descendant: tree_sitter::Node) -> bool {
    let mut n = descendant;
    loop {
        if n.id() == ancestor.id() {
            return true;
        }
        match n.parent() {
            Some(p) => n = p,
            None => return false,
        }
    }
}

/// Extract the textual content of a string-literal AST node.
///
/// Supports two extraction strategies, tried in order:
/// 1. **Recursive child search** — walk named children looking for a
///    `short_string_content` node (the grammar's canonical inner-text
///    node for `"..."` / `'...'` strings). This is the most reliable
///    approach and matches what `goto.rs` / `summary_builder.rs` used.
/// 2. **Quote stripping** — if no `short_string_content` child exists
///    (e.g. the grammar version differs), fall back to stripping a
///    matching pair of `"` or `'` from the raw node text. This was the
///    original `hover.rs` strategy.
///
/// The node may be a `string` node directly, or any ancestor that
/// contains one (the recursive walk handles both). If `node` is an
/// `expression_list`, callers should unwrap it first.
pub fn extract_string_literal(node: tree_sitter::Node, source: &[u8]) -> Option<String> {
    // Strategy 1: recursive search for `short_string_content` child.
    fn find_string_content(n: tree_sitter::Node, source: &[u8]) -> Option<String> {
        if n.kind().starts_with("short_string_content") {
            return Some(node_text(n, source).to_string());
        }
        for i in 0..n.named_child_count() {
            if let Some(child) = n.named_child(i as u32) {
                if let Some(s) = find_string_content(child, source) {
                    return Some(s);
                }
            }
        }
        None
    }

    if let Some(s) = find_string_content(node, source) {
        return Some(s);
    }

    // Strategy 2: strip matching quotes from the raw text.
    if node.kind() == "string" {
        let text = node_text(node, source);
        if text.len() >= 2 {
            let bytes = text.as_bytes();
            let first = bytes[0];
            let last = bytes[text.len() - 1];
            if (first == b'"' || first == b'\'') && first == last {
                return Some(text[1..text.len() - 1].to_string());
            }
        }
    }

    None
}

/// Extract individual argument-expression nodes from a `function_call`'s
/// `arguments` node.
///
/// Handles the three grammar forms:
/// - Paren form `f(a, b)` — the `arguments` node contains an
///   `expression_list` child whose named children are the actual args.
/// - Table form `f{...}` — the `arguments` node itself is the single arg.
/// - String form `f "x"` — the `arguments` node itself is the single arg.
///
/// For the paren form, if the `expression_list` is absent (zero-arg call),
/// returns an empty vector.
pub fn extract_call_arg_nodes<'tree>(
    args: tree_sitter::Node<'tree>,
    source: &[u8],
) -> Vec<tree_sitter::Node<'tree>> {
    // Non-paren form: the `arguments` node IS the single argument.
    if source.get(args.start_byte()).copied() != Some(b'(') {
        return vec![args];
    }
    // Paren form: look for `expression_list` child.
    let mut exprs = Vec::new();
    for i in 0..args.named_child_count() {
        if let Some(child) = args.named_child(i as u32) {
            if child.kind() == "expression_list" {
                for j in 0..child.named_child_count() {
                    if let Some(e) = child.named_child(j as u32) {
                        exprs.push(e);
                    }
                }
            } else {
                // Some grammars expose args directly without an
                // `expression_list` wrapper; still count each named
                // child as an arg.
                exprs.push(child);
            }
        }
    }
    exprs
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn byte_to_utf16_ascii() {
        assert_eq!(byte_col_to_utf16_col(b"hello", 0), 0);
        assert_eq!(byte_col_to_utf16_col(b"hello", 3), 3);
        assert_eq!(byte_col_to_utf16_col(b"hello", 5), 5);
    }

    #[test]
    fn byte_to_utf16_bmp_chinese() {
        // 中 is U+4E2D (BMP, 1 UTF-16 unit, 3 UTF-8 bytes)
        let line = "中abc".as_bytes();
        assert_eq!(byte_col_to_utf16_col(line, 0), 0);
        assert_eq!(byte_col_to_utf16_col(line, 3), 1); // past 中
        assert_eq!(byte_col_to_utf16_col(line, 4), 2);
        assert_eq!(byte_col_to_utf16_col(line, 6), 4); // end
    }

    #[test]
    fn byte_to_utf16_astral_emoji() {
        // 👋 is U+1F44B (astral, 2 UTF-16 units, 4 UTF-8 bytes)
        let line = "👋x".as_bytes();
        assert_eq!(byte_col_to_utf16_col(line, 0), 0);
        assert_eq!(byte_col_to_utf16_col(line, 4), 2);
        assert_eq!(byte_col_to_utf16_col(line, 5), 3);
    }

    #[test]
    fn utf16_to_byte_roundtrip() {
        for line in &["abc", "中abc", "👋x", "ASCIIonly", "混合hello👋"] {
            let bytes = line.as_bytes();
            let mut byte_col = 0;
            for ch in line.chars() {
                let u16_col = byte_col_to_utf16_col(bytes, byte_col);
                let back = utf16_col_to_byte_col(bytes, u16_col);
                assert_eq!(back, byte_col, "roundtrip at {:?} byte {}", line, byte_col);
                byte_col += ch.len_utf8();
            }
        }
    }

    #[test]
    fn apply_text_edit_single_line_insert() {
        let mut text = String::from("hello world");
        // Insert "!" before "world" (utf-16 col 6).
        let edit = apply_text_edit(
            &mut text,
            Range {
                start: Position { line: 0, character: 6 },
                end: Position { line: 0, character: 6 },
            },
            "!",
        );
        assert_eq!(text, "hello !world");
        assert_eq!(edit.start_byte, 6);
        assert_eq!(edit.old_end_byte, 6);
        assert_eq!(edit.new_end_byte, 7);
        assert_eq!(edit.new_end_position.row, 0);
        assert_eq!(edit.new_end_position.column, 7);
    }

    #[test]
    fn apply_text_edit_out_of_range_appends_at_eof() {
        // A range starting past end-of-file must NOT silently insert at
        // byte 0 (which would corrupt the document). Instead, clamp both
        // endpoints to EOF and emit the edit as an append.
        let mut text = String::from("hello");
        let original = text.clone();
        let edit = apply_text_edit(
            &mut text,
            Range {
                start: Position { line: 99, character: 99 },
                end: Position { line: 99, character: 99 },
            },
            "!",
        );
        assert_eq!(text, format!("{}{}", original, "!"), "must append, not prepend");
        assert_eq!(edit.start_byte, original.len());
        assert_eq!(edit.old_end_byte, original.len());
        assert_eq!(edit.new_end_byte, original.len() + 1);
    }

    #[test]
    fn apply_text_edit_multi_line_replace() {
        let mut text = String::from("a\nb\nc");
        // Replace `b` (line 1 col 0..1) with "XX\nYY"
        let edit = apply_text_edit(
            &mut text,
            Range {
                start: Position { line: 1, character: 0 },
                end: Position { line: 1, character: 1 },
            },
            "XX\nYY",
        );
        assert_eq!(text, "a\nXX\nYY\nc");
        // new_end_position should be on the line containing "YY" at column 2.
        assert_eq!(edit.new_end_position.row, 2);
        assert_eq!(edit.new_end_position.column, 2);
    }

    #[test]
    fn position_to_byte_offset_with_chinese_line() {
        // LSP sends column as UTF-16 units. For line "中abc", column 3 (past
        // 中ab) should map to byte 5 (3 for 中 + 2 for ab).
        let src = "---\n中abc";
        let pos = Position { line: 1, character: 3 };
        let byte = position_to_byte_offset(src, pos).unwrap();
        assert_eq!(&src.as_bytes()[byte..byte + 1], b"c");
    }

    // Minimal parse-only helper for walk_ancestors tests; mirrors
    // `tests/test_helpers::new_parser` but avoids pulling the test
    // helpers crate into the lib's unit-test scope.
    fn parse_source(src: &str) -> tree_sitter::Tree {
        let mut parser = tree_sitter::Parser::new();
        parser
            .set_language(&tree_sitter_mylua::LANGUAGE.into())
            .expect("mylua grammar");
        parser.parse(src, None).expect("parse")
    }

    #[test]
    fn walk_ancestors_finds_enclosing_kind() {
        // `function foo() return 1 end` — starting from the `1` number
        // literal, find the enclosing `function_declaration`.
        let tree = parse_source("function foo() return 1 end\n");
        let root = tree.root_node();
        let number = root.descendant_for_byte_range(22, 22).expect("number node");
        assert_eq!(number.kind(), "number");
        let func = walk_ancestors(number, |p| {
            if p.kind() == "function_declaration" {
                Some(p)
            } else {
                None
            }
        });
        assert!(func.is_some(), "should find function_declaration ancestor");
    }

    #[test]
    fn walk_ancestors_returns_none_when_pred_never_matches() {
        let tree = parse_source("local x = 1\n");
        let root = tree.root_node();
        let number = root.descendant_for_byte_range(10, 10).expect("number");
        let hit: Option<()> = walk_ancestors(number, |p| {
            // A kind that doesn't exist in Lua AST.
            if p.kind() == "nonexistent_node_kind" {
                Some(())
            } else {
                None
            }
        });
        assert!(hit.is_none());
    }

    #[test]
    fn walk_ancestors_caps_at_limit_on_deep_tree() {
        // Build a source with enough nested parentheses to exceed the
        // walk limit. Each `(` adds a `parenthesized_expression`
        // wrapper, so `(...(((1)))...)` with N opens gives a chain
        // whose inner `1` sits >= N ancestors down.
        let depth = ANCESTOR_WALK_LIMIT + 20;
        let mut src = String::from("local x = ");
        for _ in 0..depth {
            src.push('(');
        }
        src.push('1');
        for _ in 0..depth {
            src.push(')');
        }
        src.push('\n');

        let tree = parse_source(&src);
        let root = tree.root_node();
        // Locate the `1` — sitting deep inside the parens.
        let number_byte = "local x = ".len() + depth;
        let number = root
            .descendant_for_byte_range(number_byte, number_byte)
            .expect("number node");
        assert_eq!(number.kind(), "number");

        let mut calls = 0usize;
        let hit: Option<()> = walk_ancestors(number, |_p| {
            calls += 1;
            None
        });
        assert!(hit.is_none(), "never matching pred should return None");
        assert_eq!(
            calls, ANCESTOR_WALK_LIMIT,
            "walk must cap iterations at ANCESTOR_WALK_LIMIT ({}), got {}",
            ANCESTOR_WALK_LIMIT, calls,
        );
    }

    #[test]
    fn line_index_cache_invalidates_on_different_source() {
        // Regression guard for the thread-local line-start cache. Exercises:
        //   - fresh build for source A (cache miss)
        //   - repeated queries on A (cache hits)
        //   - switch to a structurally different source B (cache must
        //     rebuild, not serve stale offsets from A)
        //   - switch back to A (either rebuild or already-stale-proof)
        // Uses the public wrappers instead of calling `byte_offset_of_line`
        // directly so the test also verifies the end-to-end LSP
        // position → byte offset path that every tree-sitter range
        // conversion depends on.
        let src_a = "aaa\nbbb\nccc"; // 3 lines (no trailing newline)
        let src_b = "x\ny\nz\nw\nv"; // 5 lines (no trailing newline)

        // Prime cache with src_a and verify each line start.
        for (row, expected) in [(0u32, 0usize), (1, 4), (2, 8)] {
            let pos = Position { line: row, character: 0 };
            assert_eq!(
                position_to_byte_offset(src_a, pos),
                Some(expected),
                "src_a row {}", row
            );
        }
        // Out-of-range row yields None (past the last line).
        assert_eq!(
            position_to_byte_offset(src_a, Position { line: 3, character: 0 }),
            None,
            "src_a row 3 should be None (out of range, no trailing newline)"
        );

        // Switch to src_b — cache must rebuild with B's line starts.
        // If it didn't, row 4 would either return None (A had only 3
        // lines) or the stale offset from A.
        for (row, expected) in [(0u32, 0usize), (1, 2), (2, 4), (3, 6), (4, 8)] {
            let pos = Position { line: row, character: 0 };
            assert_eq!(
                position_to_byte_offset(src_b, pos),
                Some(expected),
                "src_b row {}", row
            );
        }

        // Switch back to src_a — must still produce A's offsets.
        assert_eq!(
            position_to_byte_offset(src_a, Position { line: 1, character: 0 }),
            Some(4),
            "src_a row 1 after round-trip through src_b"
        );
    }

    #[test]
    fn truncate_respects_utf8_char_boundary() {
        // Regression for panic "byte index N is not a char boundary;
        // it is inside '动' (bytes ...)". The original implementation
        // did `&s[..max]` with a raw byte index, which explodes if the
        // cut falls inside a multibyte UTF-8 character. We now snap the
        // cut down to the nearest char boundary.
        //
        // Input crafted so `max == 40` lands inside the 3-byte '动'
        // (U+52A8): "nil\r\nend\r\n\r\n---获取七日签到BP活动..." where
        // '动' occupies bytes 38..41, so max=40 is mid-char.
        let s = "nil\r\nend\r\n\r\n---获取七日签到BP活动详细数据\r\nfunction NoviceRewardModel";
        assert!(s.len() > 40, "precondition: source longer than cut point");
        let t = truncate(s, 40);
        assert!(t.ends_with("..."), "must include ellipsis when truncated");
        // Ensure the result ends cleanly before '动' (U+52A8, bytes 38..41).
        // After `\n → \\n` expansion the prefix length is not directly
        // comparable to the original cut, so instead check the char
        // straddling the boundary was dropped (not partially sliced).
        let prefix = t.strip_suffix("...").unwrap();
        assert!(
            !prefix.contains('动'),
            "prefix should not contain the char straddling the cut: {:?}",
            prefix
        );

        // ASCII path stays unchanged.
        assert_eq!(truncate("hello", 40), "hello");
        assert_eq!(truncate("hello\nworld", 40), "hello\\nworld");

        // Exactly-on-boundary cut works: '中' is 3 bytes (0..3).
        // max=3 is a valid boundary, so the prefix is '中' and ellipsis appended.
        let z = truncate("中国人民", 3);
        assert_eq!(z, "中...");
    }
}
